#!/bin/sh
export image="$1"
export keyfile="$2"

test -e "$keyfile" || {
	echo "keyfile not found"
	exit 1
}

./vm-run "
	echo Installing $keyfile..
	mkdir -p /root/.ssh/ 2>/dev/null
	chmod 0700 /root/.ssh
	echo \"$(cat "$keyfile")\" >> /root/.ssh/authorized_keys
	chmod 0600 /root/.ssh/authorized_keys
"
