#!/bin/sh
die() {
	echo "error: $1"
	exit 1
}

reboot() {
	echo -n "Rebooting in.. "
	for i in $(seq 10 -1 1)
	do
		echo -n "$i.. "
		sleep 1
	done
	echo "now"
	command reboot

	# fallback for crappy hardware
	echo "Failed to reboot, trying fallback.."
	sysctl -w kernel.sysrq=1
	echo b >/proc/sysrq-trigger
}

case "$action" in
recv)
	# this is the client role
	# it is executed on a target machine that is being flashed
	echo -n "Detecting available disks.. "
	disks=$(fdisk -l 2>/dev/null \
			| grep '^Disk /dev/' \
			| sed 's/^Disk //; s/:.*//')
	test "$disks" = "" && die "no disks found"
	echo "$disks" | sed '1s/^/[/; 1s/$/]/' | xargs

	disk=$(echo "$disks" | sed 1q)

	echo Downloading..
	cat >"$disk"

	sync
	reboot
	;;

send-check)
	;;

send)
	cat
	;;

send-post)
	;;
esac
